const teamData = {
  Minhaz_Nawas: require("../assets/organisers/Minhaz_Nawas.jpg"),
  Akhil_antony: require("../assets/organisers/ANTONY SEBASTIAN.jpg"),
  MD_Adil: require("../assets/organisers/ADIL SALFI.jpeg"),
  sreejith: require("../assets/organisers/Sreejith R R.jpg"),
  harish: require("../assets/organisers/Harish Madireddi.jpeg"),
  aman: require("../assets/organisers/Aman Jagtap.webp"),
  mayuri: require("../assets/organisers/Mayuri_chourasia  Rajesh.jpg"),
  rishi: require("../assets/organisers/Ravulapelly Rishi Kumar.jpg"),
  Diva: require("../assets/organisers/Diva Jaiwar.jpg"),
  manikanta: require("../assets/organisers/Uppulapu Manikanta.jpg"),
  mayur: require("../assets/organisers/MAYUR JAGALPURE MANOJ.jpg"),
  pradeep: require("../assets/organisers/Pradeep Mundlik.jpg"),
  stephen: require("../assets/organisers/STEPHEN V S.jpg"),
  sreevani: require("../assets/organisers/CHIKKALAWAR SREEVANI.jpg"),
  anurag: require("../assets/organisers/MANDA ANURAG.jpg"),
  sujith: require("../assets/organisers/Sai Sujith Reddy Sandhi.jpg"),
  riyaann: require("../assets/organisers/Riya Ann Easow.jpeg"),
  bharath: require("../assets/organisers/Chamarthi Bharath.jpg"),
  shravya: require("../assets/organisers/KUMMARI SHRAVYA.jpg"),
  akshat: require("../assets/organisers/Akshat Jain.jpg"),
  kartik: require("../assets/organisers/Kartik Agrawal.jpeg"),
  hiya: require("../assets/organisers/Hiya Mehta.jpg"),
  vishwajith: require("../assets/organisers/Bommineni Vishwajith Reddy.jpg"),
  dhatri: require("../assets/organisers/Velma Dhatri Reddy.jpeg"),
  harishankar: require("../assets/organisers/Harishankar - Harishankar M.jpeg"),
  sreeya: require("../assets/organisers/sreeya - TIPIRISETTY SREEYA.jpeg"),
  pushkal: require("../assets/organisers/Pushkal Mishra.jpg"),
  govind: require("../assets/organisers/Govind Pal.jpg"),
  viren: require("../assets/organisers/Viren.jpeg"),
  rishit: require("../assets/organisers/RISHIT SINGH SOMVANSHI.jpg"),
  siriS: require("../assets/organisers/Siri Shankarathota.jpg"),
  pragya: require("../assets/organisers/Pragya Yadav.jpg"),
  adheena: require("../assets/organisers/Adheena S.jpg"),
  chaitanya: require("../assets/organisers/Malakala Chaitanya.jpeg"),
  loukik: require("../assets/organisers/Loukik Pradip Kalbande.jpg"),
  gatikrushna: require("../assets/organisers/Gatikrushna Mohapatra.jpg"),
  aayush: require("../assets/organisers/Aayush_Prabhu.jpg"),
  ajay: require("../assets/organisers/AJAY PATEL.jpg"),
  arun: require("../assets/organisers/RONGALA ARUN SIDDARDHA.jpg"),
  suryaansh: require("../assets/organisers/Suryaansh Jain.jpeg"),
  surya: require("../assets/organisers/SURYA SUDEEP.jpg"),
  ritik: require("../assets/organisers/Ritik Pal.jpg"),
  jaswanth: require("../assets/organisers/Jaswanth beere.jpg"),
  bhanu: require("../assets/organisers/CHEMIKALA BHANU TEJA REDDY.jpeg"),
  ramanathan: require("../assets/organisers/RAMANATHAN ANNAMALAI.jpg"),
  uday: require("../assets/organisers/P Uday Ratna Sekhar.jpg"),
  uttej: require("../assets/organisers/Uttej.png"),
  pranav: require("../assets/organisers/Pericherla Pranav Varma.jpeg"),
  aravind: require("../assets/organisers/Aravind Siddhartha Kotichintala.jpg"),
  sathvika: require("../assets/organisers/Marri Sathvika.jpg"),
  sanaAnesha: require("../assets/organisers/Sana Anesha Shabbeer.jpg"),
  hadiAfnan: require("../assets/organisers/HADI AFNAN.jpg"),
  ahinraj: require("../assets/organisers/AHINRAJ M S.jpg"),
  divyaM: require("../assets/organisers/DIVYA M.jpg"),
  nabeelM: require("../assets/organisers/NABEEL MOHAMMED P T.JPG"),
  // ravindra: require("../assets/organisers/.jpg"),
  BRohit: require("../assets/organisers/Bevara Rohit.jpg"),
  abhishek: require("../assets/organisers/Abhishek Ghosh.jpg"),
  BAnvitha: require("../assets/organisers/Anvitha.jpg"),
  shreyas: require("../assets/organisers/Shreyas Rajesh Wankhede.jpeg"),
  shubham: require("../assets/organisers/Subham Mohanty.jpg"),
  suryaTeja: require("../assets/organisers/CHERUKUSURYA TEJA.jpg"),
  dheeraj: require("../assets/organisers/Dheeraj M.jpeg"),
  dhanushikaa: require("../assets/organisers/Dhanushikaa S.jpg"),
  subiksha: require("../assets/organisers/Subiksha Gayathiri K K.jpg"),
  yashRamteke: require("../assets/organisers/Yash Rajesh Ramteke.jpeg"),
  mouktika: require("../assets/organisers/Cherukupalli Sai Malini Mouktika.jpg"),
  nanda: require("../assets/organisers/Nanda Kishore Reddy Mummadi.jpg"),
  // gaurang: require("../assets/organisers/.jpg"),
  raniKR: require("../assets/organisers/raniKR.jpeg"),
  // abhayKumar: require("../assets/organisers/.jpg"),
  anusha: require("../assets/organisers/Anusha.jpg"),
  // rohitS: require("../assets/organisers/.jpg"),
  krithik: require("../assets/organisers/Kritik.jpg"),
  // kaustubh: require("../assets/organisers/.jpg"),
  jayBhanushali: require("../assets/organisers/Jay Bhanushali.JPG"),
  kanak: require("../assets/organisers/Kanak.jpg"),
  jalaPrajash: require("../assets/organisers/Jala Prajash.jpg"),
};

export default teamData;
